;Valores
(display "perimetro del triángulo")
(display " de lado 1") 
(define l(read))
(display " de lado 2 ")
(define m(read))
(display " de lado 3")
(define n(read))
(define Pt (+(+ l m) n))
(display "Área del triángulo")
(display " de base") 
(define b(read))
(newline)
(display "de altura")
(define h(read))
(newline)
(define At (/(* b h)2))
(display "perimetro del cuadrado")
(display " de lado") 
(define a(read))
(newline)
(define Pc (* 4 a))
(display "El Area del cuadrado")
(display " de lado: ")
(define a(read))
(display " es: ")
(newline)
(define Ac (sqr a))
(display "perimetro del rectángulo")
(display " de base") 
(define b(read))
(display " de altura")
(define h(read))
(newline)
(define Pr (+(* 2 b) (* 2 h)))
(display "área del rectángulo")
(display " de base") 
(define b(read))
(display " de altura")
(define h(read))
(define Ar (* b h))
(display "Perimetro del rombo")
(display " de lado") 
(define a(read))
(define Prombo (* 4 a))
(display "área del Rombo")
(display " de Diagonal Mayor") 
(define D(read))
(display " de diagonal menor")
(define d(read))
(newline)
(define Arombo (/ (* D d)2))
(display "perimetro del Romboide")
(display " de base") 
(define b(read))
(display " de altura")
(define h(read))
(define Promboide (+(* 2 b) (* 2 h)))
(display "Área del Romboide")
(display " de base") 
(define b(read))
(display " de altura")
(define h(read))
(define Aromboide (* b h))
(display "Perimetro del Trapecio")
(display " de lado 1: ") 
(define l(read))
(display " de lado 2: ")
(define m(read))
(display " de lado 3: ")
(define n(read))
(display " de lado 4: ")
(define o(read))
(newline)
(define Ptrapecio (+(+ l m) (+ n o)))
(display "Área de un Trapecio")
(display " de base mayor") 
(define B(read))
(display " de base menor")
(define b(read))
(display "de altura")
(define h(read))
(newline)
(define Atrapecio(/(*(+ B b)h)2))
;tabla
(display "\t\t\n|    Forma      |       Elementos       |      Perimetro        |     área      | ")
(display "\t\n--------------------------------------------------------------------------------|\n")
(display "|triángulo\t|") (display "b: base\t\t|\t\t\t|\t\t|\n\t\t|h: altura\t\t|\t\t\t|\t\t|\n\t\t|l: lado1\t\t|\t\t\t|\t\t|\n\t\t|m: lado2\t\t|\t\t\t|\t\t|\n\t\t|n: lado3\t\t|")(display Pt)(display "\t\t\t|")(display At)(display "\t\t|\n")
(display "|-------------------------------------------------------------------------------|\n")
(display "|Cuadrado\t|")(display "a: lado\t\t|")(display Pc)(display "\t\t\t|")(display Ac)(display "\t\t|\n")
(display "|-------------------------------------------------------------------------------|\n")
(display "|Rectángulo\t|")(display "b: base\t\t|\t\t\t|\t\t|\n\t\t|h: altura\t\t|")(display Pr)(display "\t\t\t|")(display Ar)(display "\t\t|\n")
(display "|-------------------------------------------------------------------------------|\n")
(display "|Rombo\t\t|")(display "a: lado\t\t|\t\t\t|\t\t|\n\t\t|d: diagonal menor\t|\t\t\t|\t\t|\n\t\t|D: diagonal mayor\t|")(display Prombo)(display "\t\t\t|")(display Arombo)(display "\t\t|\n")
(display "|-------------------------------------------------------------------------------|\n")
(display "|Romboide\t|")(display "b: base\t\t|\t\t\t|\t\t|\n\t\t|h: altura\t\t|")(display Promboide)(display "\t\t\t|")(display Aromboide)(display "\t\t|\n")
(display "|-------------------------------------------------------------------------------|\n")
(display "|Trapecio\t|")(display "b: base menor\t\t|\t\t\t|\t\t|\n\t\t|B: base mayor\t\t|\t\t\t|\t\t|\n\t\t|h: altura\t\t|\t\t\t|\t\t|\n\t\t|l: lado1\t\t|\t\t\t|\t\t|\n\t\t|m: lado2\t\t|\t\t\t|\t\t|\n\t\t|n: lado3\t\t|\t\t\t|\t\t|\n\t\t|o: lado4\t\t|")(display Pr)(display "\t\t\t|")(display Ar)(display "\t\t|\n")
(display "|-------------------------------------------------------------------------------|\n")