(define (PROBLEMA1)
  (define (mayor a b)
    (cond
      ((> a b) a)
      ((> b a) b)
      (else "Son iguales")))
  (display (mayor 4 5))
  (newline))

(define (PROBLEMA2)
  (define (menor a b c)
    (cond
      ((and (< a b) (< a c)) a)
      ((and (< b a) (< b c)) b)
      ((and (< c a) (< c b)) c)
      (else "Ingrese un valor válido")))
  (display (menor 3 2 6))
  (newline))

(define (PROBLEMA3)
  (define (mayor a b c d)
    (cond
      ((and (> a b) (> a c) (> a d)) a)
      ((and (> b a) (> b c) (> b d)) b)
      ((and (> c a) (> c b) (> c d)) c)
      ((and (> d a) (> d b) (> d c)) d)
      (else "Ingrese un valor válido")))
  (display (mayor 2 1 3 4))
  (newline))

(define (PROBLEMA4)
  (define (calculadora operacion a b)
    (cond
      ((= operacion 1) (* a b))
      ((= operacion 2) (+ a b))
      ((= operacion 3) (- a b))
      ((= operacion 4) (list (abs a) (abs b)))
      (else "Operación no válida")))
  
  (define (principal)
    (display "¿Qué operación desea realizar? \n1) Multiplicación \n2) Suma \n3) Resta \n4) Valor absoluto\n")
    (define operacion (read))
    (display "\nIngrese el primer número a operar: ")
    (define a (read))
    (display "\nIngrese el segundo número a operar: ")
    (define b (read))
    (display (calculadora operacion a b))
    (newline))
  
  (principal))

(define (PROBLEMA5)
  (define (reparto salario años)
    (cond
      ((< años 1) (* salario 0.05))
      ((and (>= años 1) (< años 2)) (* salario 0.07))
      ((and (>= años 2) (< años 5)) (* salario 0.1))
      ((and (>= años 5) (< años 10)) (* salario 0.15))
      ((>= años 10) (* salario 0.2))
      (else "Ingrese un valor válido")))
  
  (define (principal)
    (display "Ingrese el salario mensual del trabajador:\n")
    (define salario (read))
    (display "\nIngrese el tiempo (en años) que lleva el trabajador en la empresa:\n")
    (define años (read))
    (display "\nEl reparto anual es: ")
    (display (reparto salario años))
    (newline))
  
  (principal))

(define (PROBLEMA6)
  (define (descuento costo marca)
    (cond
      ((and (>= costo 1000000) (= marca 2)) (- costo (* costo 0.10)))
      ((and (>= costo 1000000) (= marca 1)) (- costo (* costo 0.15)))
      ((= marca 1) (- costo (* costo 0.05)))
      ((or (< costo 1000000) (= marca 2)) (+ costo (* costo 0.20)))
      (else "Ocurrió un error")))
  
  (define (variables)
    (display "Ingrese el costo del computador: ")
    (define costo (read))
    (display "Si la marca es ABACO, ingrese 1; si es cualquier otra, ingrese 2: ")
    (define marca (read))
    (display (descuento costo marca))
    (newline))
  
  (variables))

(define (PROBLEMA7)
  (define (centenas a)
    (cond
      ((= (quotient a 100) 1) "cien ")
      ((= (quotient a 100) 2) "doscientos ")
      ((= (quotient a 100) 3) "trescientos ")
      ((= (quotient a 100) 4) "cuatrocientos ")
      ((= (quotient a 100) 5) "quinientos ")
      ((= (quotient a 100) 6) "seiscientos ")
      ((= (quotient a 100) 7) "setecientos ")
      ((= (quotient a 100) 8) "ochocientos ")
      ((= (quotient a 100) 9) "novecientos ")
      (else "")))

  (define (unidades a)
    (cond
      ((= a 1) "uno")
      ((= a 2) "dos")
      ((= a 3) "tres")
      ((= a 4) "cuatro")
      ((= a 5) "cinco")
      ((= a 6) "seis")
      ((= a 7) "siete")
      ((= a 8) "ocho")
      ((= a 9) "nueve")
      (else "")))

  (define (decenas a)
    (let ((d (quotient (modulo a 100) 10))
          (u (modulo a 10)))
      (cond
        ((= d 1)
         (list-ref '("diez " "once " "doce " "trece " "catorce " "quince " "dieciséis " "diecisiete " "dieciocho " "diecinueve ") u))
        ((= d 2) (if (= u 0) "veinte " (string-append "veinti" (unidades u))))
        ((= d 3) (if (= u 0) "treinta " (string-append "treinta y " (unidades u))))
        ((= d 4) (if (= u 0) "cuarenta " (string-append "cuarenta y " (unidades u))))
        ((= d 5) (if (= u 0) "cincuenta " (string-append "cincuenta y " (unidades u))))
        ((= d 6) (if (= u 0) "sesenta " (string-append "sesenta y " (unidades u))))
        ((= d 7) (if (= u 0) "setenta " (string-append "setenta y " (unidades u))))
        ((= d 8) (if (= u 0) "ochenta " (string-append "ochenta y " (unidades u))))
        ((= d 9) (if (= u 0) "noventa " (string-append "noventa y " (unidades u))))
        (else ""))))

  (define (principal)
    (display "Escriba un número de máximo 3 cifras (0 a 999): ")
    (define a (read))
    (if (and (>= a 0) (<= a 999))
        (begin
          (if (= a 0) 
              (display "cero")
              (begin
                (display (centenas a))
                (if (and (>= (modulo a 100) 10) (<= (modulo a 100) 19))
                    (display (decenas a))
                    (begin
                      (display (decenas a))
                      (display (unidades (modulo a 10)))))))
          (newline))
        (display "Ingrese un número dentro del rango.\n")))

  (principal))

(define (llamar pron)
  (cond
    ((= pron 1) (PROBLEMA1))
    ((= pron 2) (PROBLEMA2))
    ((= pron 3) (PROBLEMA3))
    ((= pron 4) (PROBLEMA4))
    ((= pron 5) (PROBLEMA5))
    ((= pron 6) (PROBLEMA6))
    ((= pron 7) (PROBLEMA7))
    (else (display "Número de problema no válido.\n"))))

(display "Ingrese el número del problema que desea ejecutar: ")
(llamar (read))
